[package]
name = "bureau"
categories.workspace = true
description.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bureau-lifecycle = { path = "../bureau-lifecycle" }
bureau-plugin = { path = "../bureau-plugin" }
clap.workspace = true
nix = { workspace = true, features = ["fs", "process", "signal"] }
ratatui.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
thiserror.workspace = true
tokio.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "bureau"
path = "src/main.rs"
